import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

/**
 * API Route: POST /api/install/save-config
 * Save Supabase credentials to .env.local file during installation
 */
export async function POST(request) {
  try {
    const { supabaseUrl, supabaseAnonKey, supabaseServiceRoleKey } = await request.json();

    if (!supabaseUrl || !supabaseAnonKey || !supabaseServiceRoleKey) {
      return NextResponse.json(
        { error: 'Missing required credentials' },
        { status: 400 }
      );
    }

    // Create .env.local content
    const envContent = `# Supabase Configuration
# Generated by NotWordPress Installation Wizard
# Last updated: ${new Date().toISOString()}

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceRoleKey}

# IMPORTANT: Copy these values to your Vercel project's environment variables
# for production deployment. Go to:
# Vercel Dashboard → Your Project → Settings → Environment Variables
`;

    // Write to .env.local file in project root
    const envPath = path.join(process.cwd(), '.env.local');
    fs.writeFileSync(envPath, envContent, 'utf8');

    return NextResponse.json({
      success: true,
      message: 'Configuration saved to .env.local successfully',
      envContent: envContent // Return it so we can show it to the user
    });
  } catch (error) {
    console.error('Error saving config:', error);
    return NextResponse.json(
      { error: 'Failed to save configuration: ' + error.message },
      { status: 500 }
    );
  }
}
